
development:
  adapter: mysql2
  encoding: utf8
  database: heroku_e2927a4c4f81c6c
  username: b474241013c486
  password: 6cd98647

production:
  adapter: mysql2
  encoding: utf8
  database: heroku_e2927a4c4f81c6c
  username: b474241013c486
  password: 6cd98647

